### ISSUE TITLE
html5 compilation error

### ISSUE THREAD

**Issue by lenis0012** [czyzby/gdx-lml#41]
First of all, i wanted to thank you for actively maintaining the library.
you're a hero <3

Secondly, I can't compile my game for html5, it gives a kiwi error =(
http://pastebin.com/Zr5dyUuv

**Comment by czyzby** [comment]
Are you using an older/newer version of LibGDX than Kiwi is compiled against? `OrderedMap` constructor changed in LibGDX 1.9.4 (I think). If you're using LibGDX 1.9.3 (or older), use `gdx-kiwi 1.7.1.9.3`. If you're using the latest LibGDX, switch to beta release - `gdx-kiwi 1.8.1.9.3-b1`.

**Comment by lenis0012** [comment]
It does compile with kiwi 1.8
my bad, i should have looked for beta releases first.
i suppose you can close the issue.

thank you =)

**Comment by lenis0012** [comment]
@czyzby I did get another error with autumn on android packaging tho
http://pastebin.com/3jHE3chg

**Comment by lenis0012** [comment]
seems to be resolved when adding     
packagingOptions {
        exclude 'META-INF/robovm/ios/robovm.xml'
    }

to android/build.gradle

**Comment by czyzby** [comment]
Yes, this is a common issue. Android does not handle duplicate files very well, but in order to enable RoboVM reflection of some classes, `robovm.xml` is required in pretty much every library. That's why our [gdx-setup](https://github.com/czyzby/gdx-setup/) includes [this conguration](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L116-L130) in the Android Gradle file.
